/**
 * @tashfeen/shared-types — enums/case.enums.ts
 * Matches Prisma schema: CaseStatus, ProcessingCaseStage
 */

export enum CaseStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  DOCUMENTATION = 'DOCUMENTATION',
  PROCESSING = 'PROCESSING',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
  COMPLETED = 'COMPLETED',
  ON_HOLD = 'ON_HOLD',
}

export enum ProcessingCaseStage {
  INTAKE_PENDING = 'INTAKE_PENDING',
  DOCUMENTS_COLLECTION = 'DOCUMENTS_COLLECTION',
  DOCUMENTS_UNDER_REVIEW = 'DOCUMENTS_UNDER_REVIEW',
  DOCUMENTS_INCOMPLETE = 'DOCUMENTS_INCOMPLETE',
  DOCUMENTS_COMPLETE = 'DOCUMENTS_COMPLETE',
  READY_FOR_SUBMISSION = 'READY_FOR_SUBMISSION',
  SUBMITTED = 'SUBMITTED',
  UNDER_AUTHORITY_REVIEW = 'UNDER_AUTHORITY_REVIEW',
  ADDITIONAL_INFO_REQUESTED = 'ADDITIONAL_INFO_REQUESTED',
  DECISION_RECEIVED = 'DECISION_RECEIVED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  APPEAL_IN_PROGRESS = 'APPEAL_IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
